//! Codeberg #237: golden vectors for the Telemeter codec.
//!
//! Every capture here was generated by `gen_telemetry_vectors.py` running the
//! REAL Sideband `sense.py` (commit `2000d81`), and every capture was fed back
//! through `Telemeter.from_packed` at generation time with the decoded values
//! asserted against the inputs. A test that decodes a capture to the recorded
//! facts and re-encodes the facts to the same bytes has therefore proven both
//! directions against the origin implementation: our encoder's output is
//! byte-identical to what `Telemeter.packed()` emits for the same readings,
//! which is the strongest available form of "decodes in Sideband to the same
//! values". The Columba vector (`TelemeterCodec.kt`, commit `0930293`) plays
//! the same role for the second implementation: our two-sensor emit is
//! byte-identical to `packLocationTelemetry`'s output for the same fix, so
//! `unpackLocationTelemetry` reads it exactly as it reads Columba's own.

mod common;

use leviculum_lxmf::msgpack::Number;
use leviculum_lxmf::telemetry::{
    decode_stream_field_value, encode_stream_field_value, Battery, Location, PhysicalLink,
    PowerProducer, StreamEntry, Telemetry,
};

const FIXTURES: &str = include_str!("../../docs/src/appendix/lxmf/vectors/telemetry_vectors.json");

fn hex_vec(id: &str, field: &str) -> Vec<u8> {
    hex::decode(common::fixture_from(FIXTURES, id, field)).unwrap()
}

fn int(id: &str, field: &str) -> i64 {
    common::fixture_from(FIXTURES, id, field).parse().unwrap()
}

fn float(id: &str, field: &str) -> f64 {
    common::fixture_from(FIXTURES, id, field).parse().unwrap()
}

/// The canonical tracker readings, built from the fixture's recorded facts.
/// The location integers were read back out of the capture by the generator
/// (`struct.unpack` on the wire blobs), so Python's float rounding cannot
/// skew them.
fn tracker_telemetry() -> Telemetry {
    let id = "VEC-TELE-TRACKER";
    Telemetry {
        time: Some(int(id, "time_utc")),
        location: Some(fixture_location(id)),
        battery: Some(Battery {
            charge_percent: Number::Float(float(id, "battery_charge_percent")),
            charging: Some(true),
            temperature: None,
        }),
        physical_link: Some(PhysicalLink {
            rssi: Some(Number::Int(int(id, "link_rssi"))),
            snr: Some(Number::Float(float(id, "link_snr"))),
            q: Some(Number::Int(int(id, "link_q"))),
        }),
        temperature: Some(Number::Float(float(id, "temperature_c"))),
        power_production: Some(vec![
            PowerProducer {
                type_label: Some(common::fixture_from(FIXTURES, id, "power_0_label").into()),
                power: Number::Float(float(id, "power_0_watts")),
                custom_icon: Some(common::fixture_from(FIXTURES, id, "power_0_icon").into()),
            },
            PowerProducer {
                type_label: None,
                power: Number::Float(float(id, "power_1_watts")),
                custom_icon: None,
            },
        ]),
    }
}

fn fixture_location(id: &str) -> Location {
    Location {
        latitude_e6: int(id, "latitude_e6") as i32,
        longitude_e6: int(id, "longitude_e6") as i32,
        altitude_e2: int(id, "altitude_e2") as i32,
        speed_e2: int(id, "speed_e2") as u32,
        bearing_e2: int(id, "bearing_e2") as i32,
        accuracy_e2: int(id, "accuracy_e2") as u16,
        last_update: int(id, "last_update"),
    }
}

#[test]
fn tracker_capture_round_trips_byte_identically() {
    let packed = hex_vec("VEC-TELE-TRACKER", "packed_hex");
    let expected = tracker_telemetry();
    assert_eq!(Telemetry::decode(&packed).unwrap(), expected);
    assert_eq!(expected.encode(), packed);
}

#[test]
fn southwest_sign_edges_round_trip() {
    let id = "VEC-TELE-SOUTHWEST";
    let packed = hex_vec(id, "packed_hex");
    let location = fixture_location(id);
    assert!(location.latitude_e6 < 0, "southern hemisphere");
    assert!(location.longitude_e6 < 0, "western hemisphere");
    assert!(location.altitude_e2 < 0, "below sea level");
    let expected = Telemetry {
        time: Some(int(id, "time_utc")),
        location: Some(location),
        ..Telemetry::default()
    };
    assert_eq!(Telemetry::decode(&packed).unwrap(), expected);
    assert_eq!(expected.encode(), packed);
}

/// The origin cannot emit these bounds (its `struct.pack` raises and the
/// reading collapses to nil), but its decoder accepts them — the generator
/// proved that with `from_packed`. Our saturating constructor produces
/// exactly the accepted bounds.
#[test]
fn saturated_wire_bounds_round_trip() {
    let id = "VEC-TELE-SATURATED";
    let packed = hex_vec(id, "packed_hex");
    let location = Location::saturating(
        int(id, "latitude_e6"),
        int(id, "longitude_e6"),
        int(id, "altitude_e2"),
        u32::MAX as i64 + 4_000, // speed far above the unsigned bound
        int(id, "bearing_e2"),
        70_000, // accuracy above the 16-bit ceiling
        int(id, "last_update"),
    );
    assert_eq!(location.speed_e2, u32::MAX);
    assert_eq!(location.accuracy_e2, u16::MAX);
    assert_eq!(location, fixture_location(id));
    let expected = Telemetry {
        time: Some(int(id, "time_utc")),
        location: Some(location),
        ..Telemetry::default()
    };
    assert_eq!(Telemetry::decode(&packed).unwrap(), expected);
    assert_eq!(expected.encode(), packed);
}

#[test]
fn saturating_clamps_the_low_bounds_too() {
    let location = Location::saturating(i64::MIN, i64::MAX, i64::MIN, -125, i64::MAX, -1, 7);
    assert_eq!(location.latitude_e6, i32::MIN);
    assert_eq!(location.longitude_e6, i32::MAX);
    assert_eq!(location.altitude_e2, i32::MIN);
    assert_eq!(location.speed_e2, 0, "negative speed saturates to zero");
    assert_eq!(location.bearing_e2, i32::MAX);
    assert_eq!(location.accuracy_e2, 0);
    assert_eq!(location.last_update, 7);
}

/// SID -> nil is the second encoding of absence: sensor present, no reading.
/// Sideband emits it for every active sensor whose data is unavailable;
/// refusing it would be our defect (docs/src/concepts/telemetry.md).
#[test]
fn nil_reading_decodes_as_absent() {
    let id = "VEC-TELE-NIL-READING";
    let decoded = Telemetry::decode(&hex_vec(id, "packed_hex")).unwrap();
    assert_eq!(
        decoded,
        Telemetry {
            time: Some(int(id, "time_utc")),
            ..Telemetry::default()
        }
    );
}

#[test]
fn unknown_sensor_is_skipped_not_rejected() {
    let id = "VEC-TELE-UNKNOWN-SENSOR";
    let decoded = Telemetry::decode(&hex_vec(id, "packed_hex")).unwrap();
    assert_eq!(
        decoded,
        Telemetry {
            time: Some(int(id, "time_utc")),
            location: Some(fixture_location(id)),
            ..Telemetry::default()
        }
    );
}

/// `Battery.unpack` treats the temperature element as optional and passes
/// `charging` through untyped; our accept set matches.
#[test]
fn short_battery_list_is_tolerated() {
    let id = "VEC-TELE-SHORT-BATTERY";
    let decoded = Telemetry::decode(&hex_vec(id, "packed_hex")).unwrap();
    assert_eq!(
        decoded.battery,
        Some(Battery {
            charge_percent: Number::Int(int(id, "battery_charge_percent")),
            charging: Some(true),
            temperature: None,
        })
    );
}

/// Both directions against the second implementation: the capture is what
/// Columba's `packLocationTelemetry` puts on the wire for this fix, and our
/// emit of the same two sensors reproduces it byte for byte — so Columba's
/// `unpackLocationTelemetry` reads our output exactly as it reads its own.
#[test]
fn columba_capture_round_trips_byte_identically() {
    let id = "VEC-TELE-COLUMBA";
    let packed = hex_vec(id, "packed_hex");
    let expected = Telemetry {
        time: Some(int(id, "time_utc")),
        location: Some(fixture_location(id)),
        ..Telemetry::default()
    };
    assert_eq!(Telemetry::decode(&packed).unwrap(), expected);
    assert_eq!(expected.encode(), packed);
}

#[test]
fn field_value_wrapping_round_trips() {
    let telemetry = tracker_telemetry();
    let field_value = telemetry.encode_field_value();
    // Inside the LXMF fields map the telemetry value is a msgpack bin
    // wrapping the packed blob, because Sideband stores `telemeter.packed()`
    // bytes as the field value.
    assert_eq!(field_value[0], 0xc4);
    assert_eq!(
        Telemetry::decode_field_value(&field_value).unwrap(),
        telemetry
    );
}

#[test]
fn stream_field_value_round_trips_byte_identically() {
    let id = "VEC-TELE-STREAM";
    let packed = hex_vec(id, "packed_hex");
    let expected = vec![
        StreamEntry {
            source: hex_vec(id, "row_0_source_hex"),
            timestamp: Number::Int(int(id, "row_0_timestamp")),
            telemetry: hex_vec(id, "row_0_telemetry_hex"),
            appearance: Some(hex_vec(id, "row_0_appearance_hex")),
        },
        StreamEntry {
            source: hex_vec(id, "row_1_source_hex"),
            timestamp: Number::Float(float(id, "row_1_timestamp")),
            telemetry: hex_vec(id, "row_1_telemetry_hex"),
            appearance: None,
        },
    ];
    let decoded = decode_stream_field_value(&packed).unwrap();
    assert_eq!(decoded, expected);
    assert_eq!(encode_stream_field_value(&expected), packed);
    // The relayed blob decodes like any direct telemetry.
    assert_eq!(
        Telemetry::decode(&decoded[0].telemetry).unwrap(),
        tracker_telemetry()
    );
}

/// We emit four elements per row without exception; on read a three-element
/// row (Columba's native collector shape) decodes with no appearance, and a
/// garbage row costs that row, not the message — unlike the reference's
/// whole-message abort.
#[test]
fn stream_read_tolerates_short_and_garbage_rows() {
    let id = "VEC-TELE-STREAM-TOLERANT";
    let decoded = decode_stream_field_value(&hex_vec(id, "packed_hex")).unwrap();
    assert_eq!(decoded.len() as i64, int(id, "surviving_rows"));
    assert_eq!(decoded[0].source, hex_vec(id, "row_0_source_hex"));
    assert_eq!(decoded[0].appearance, None);
    assert_eq!(decoded[1].source, hex_vec(id, "row_1_source_hex"));
}

#[test]
fn empty_telemetry_is_an_empty_map() {
    assert!(Telemetry::default().is_empty());
    assert!(!tracker_telemetry().is_empty());
    assert_eq!(Telemetry::default().encode(), [0x80]);
    assert_eq!(Telemetry::decode(&[0x80]).unwrap(), Telemetry::default());
}

#[test]
fn non_map_and_truncated_payloads_are_errors() {
    // The only whole-payload refusals, mirroring where from_packed itself
    // returns None: not a map, or a map that ends mid-value.
    assert!(Telemetry::decode(&[]).is_err());
    assert!(
        Telemetry::decode(&[0x90]).is_err(),
        "an array is not a telemeter"
    );
    let tracker = hex_vec("VEC-TELE-TRACKER", "packed_hex");
    assert!(Telemetry::decode(&tracker[..10]).is_err());
}

#[test]
fn trailing_bytes_are_ignored_like_the_reference() {
    // Verified against the vendored umsgpack: unpackb reads one value and
    // ignores what follows, and from_packed accepts such a payload.
    let mut padded = hex_vec("VEC-TELE-TRACKER", "packed_hex");
    padded.extend_from_slice(&[0xff, 0xff]);
    assert_eq!(Telemetry::decode(&padded).unwrap(), tracker_telemetry());
}

#[test]
fn duplicate_sid_resolves_to_the_last_occurrence() {
    // {0x01: 100, 0x01: 200} — Python dict insertion keeps the last value.
    let packed = [0x82, 0x01, 0x64, 0x01, 0xcc, 0xc8];
    assert_eq!(Telemetry::decode(&packed).unwrap().time, Some(200));
}

#[test]
fn non_integer_keys_are_skipped() {
    // {"x": 1, 0x01: 5} — a non-integer key matches no SID in from_packed.
    let packed = [0x82, 0xa1, b'x', 0x01, 0x01, 0x05];
    let decoded = Telemetry::decode(&packed).unwrap();
    assert_eq!(decoded.time, Some(5));
}

/// A malformed value under a known SID costs that sensor, not the payload —
/// every reference sensor's `unpack` catches its own exceptions.
#[test]
fn malformed_known_sensor_value_is_absent_not_fatal() {
    // {0x02: [<3-byte bin>], 0x01: 9}: location blob has the wrong width.
    let packed = [0x82, 0x02, 0x91, 0xc4, 0x03, 1, 2, 3, 0x01, 0x09];
    let decoded = Telemetry::decode(&packed).unwrap();
    assert_eq!(decoded.location, None);
    assert_eq!(decoded.time, Some(9));
}
