/*
 * Thread safety and blocking model
 * ================================
 *
 * Handle sharing across threads:
 *   - A `leviculum_t` node handle is internally synchronised: the `lev_*` calls
 *     that take a `leviculum_t*` (announce, send, connect, register, stats,
 *     etc.) may be made concurrently from multiple threads. The hidden runtime
 *     and engine state are mutex-guarded.
 *   - Event draining is single-consumer: do NOT call `lev_next_event` or
 *     `lev_wait_event` for the same node from more than one thread at a time,
 *     and do not mix the two concurrently on the same node.
 *   - `lev_link_t`, `lev_identity_t`, `lev_destination_t`, and `lev_event_t`
 *     handles are not internally locked for concurrent mutation. A handle may
 *     be moved between threads, but do not call into the same handle from two
 *     threads at once. A `lev_*_free` must not race any other call on that
 *     handle.
 *   - `lev_log_set_level` / `lev_log_set_callback` are process-global and
 *     thread-safe.
 *
 * Blocking and the event fd (deadlock warning):
 *   - Calls that take a `timeout_ms` parameter (lev_announce, lev_connect,
 *     lev_link_send, lev_send_request, lev_send_response, lev_send_datagram,
 *     lev_close_link, lev_start, lev_stop, ...) block the calling thread until
 *     they complete or the timeout elapses. A negative timeout blocks forever.
 *   - These blocking calls are driven on the calling thread but depend on the
 *     node's event loop making progress. Do NOT issue a blocking `lev_*` call
 *     from the SAME thread that drains the event fd while it is mid-drain; run
 *     the poll/drain loop and the blocking calls on separate threads, or never
 *     block on the drain thread. Blocking on the drain thread can wedge both.
 *   - `lev_event_fd` returns a fd you add to your own poll/epoll/select loop;
 *     the library owns it and closes it in `lev_free` (never close it yourself).
 */


#ifndef LEVICULUM_H
#define LEVICULUM_H

/* Generated with cbindgen:0.27.0 */

/* Warning: this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

/**
 * Incoming destination: receives announces, links, and packets.
 */
#define LEV_DIRECTION_IN 0

/**
 * Outgoing destination: a source address for sending.
 */
#define LEV_DIRECTION_OUT 1

/**
 * Single destination: point-to-point, ephemeral encryption.
 */
#define LEV_DEST_SINGLE 0

/**
 * Group destination: shared-key broadcast.
 */
#define LEV_DEST_GROUP 1

/**
 * Plain destination: unencrypted.
 */
#define LEV_DEST_PLAIN 2

/**
 * Never send delivery proofs (the default).
 */
#define LEV_PROOF_NONE 0

/**
 * Emit a proof-requested event so the app decides per packet.
 */
#define LEV_PROOF_APP 1

/**
 * Automatically prove delivery of every received packet.
 */
#define LEV_PROOF_ALL 2

/**
 * Success.
 */
#define LEV_OK 0

/**
 * A required pointer argument was NULL.
 */
#define LEV_ERR_NULL_PTR -1

/**
 * An argument was malformed (bad length, unparseable string, ...).
 */
#define LEV_ERR_INVALID_ARG -2

/**
 * The caller buffer was too small; `*out_len` holds the required size.
 */
#define LEV_ERR_BUFFER_TOO_SMALL -3

/**
 * The node event loop is not running.
 */
#define LEV_ERR_NOT_RUNNING -4

/**
 * An I/O or storage error occurred.
 */
#define LEV_ERR_IO -5

/**
 * A configuration error occurred.
 */
#define LEV_ERR_CONFIG -6

/**
 * A cryptographic operation failed.
 */
#define LEV_ERR_CRYPTO -7

/**
 * No path to the destination is known; request one first.
 */
#define LEV_ERR_NO_PATH -8

/**
 * A link operation failed (closed, inactive, or handshake).
 */
#define LEV_ERR_LINK -9

/**
 * A send failed (no route, payload too large, ...).
 */
#define LEV_ERR_SEND -10

/**
 * A resource transfer operation failed.
 */
#define LEV_ERR_RESOURCE -11

/**
 * A request or response operation failed.
 */
#define LEV_ERR_REQUEST -12

/**
 * An operation timed out.
 */
#define LEV_ERR_TIMEOUT -13

/**
 * Non-fatal backpressure; retry later (mirrors EAGAIN).
 */
#define LEV_ERR_AGAIN -14

/**
 * No cached identity for the destination; wait for an announce or request a path.
 */
#define LEV_ERR_UNKNOWN_DEST -15

/**
 * A panic was caught at the FFI boundary and converted to an error.
 */
#define LEV_ERR_PANIC -127

/**
 * Catch-all for events not yet projected with their own type and accessors.
 */
#define LEV_EVENT_OTHER 0

/**
 * A validated announce was received from a peer.
 */
#define LEV_EVENT_ANNOUNCE_RECEIVED 1

/**
 * A path to a requested destination was found.
 */
#define LEV_EVENT_PATH_FOUND 2

/**
 * Deprecated, never fired. Under the auto-accept model (Python-RNS parity)
 * inbound links are accepted and proved by the core, so there is no separate
 * request event; an inbound link surfaces as `LEV_EVENT_LINK_ESTABLISHED`
 * with `lev_event_is_sender` returning 0. The numeric value is retained for
 * ABI stability.
 */
#define LEV_EVENT_LINK_REQUEST 3

/**
 * A link handshake completed. Fires for both directions; `lev_event_is_sender`
 * is the inbound indicator: 0 means an inbound link (this node is the
 * responder; the link is already accepted and proved, mint a handle with
 * `lev_accept_link`), 1 means a link this node initiated.
 */
#define LEV_EVENT_LINK_ESTABLISHED 4

/**
 * A link closed. `link_id` and `dest_hash` are set.
 */
#define LEV_EVENT_LINK_CLOSED 5

/**
 * Data arrived on a link.
 */
#define LEV_EVENT_LINK_DATA 6

/**
 * A single packet (datagram) arrived on a destination.
 */
#define LEV_EVENT_PACKET_RECEIVED 7

/**
 * Control events were dropped; the count is available via
 * `lev_event_dropped_count`.
 */
#define LEV_EVENT_CONTROL_OVERFLOW 8

/**
 * A request arrived on a link (respond with `lev_send_response`). `dest_hash`
 * is the destination the request was addressed to: several destinations may
 * register the same request path, so a responder hosting more than one needs
 * it to know which endpoint to serve.
 */
#define LEV_EVENT_REQUEST_RECEIVED 9

/**
 * A response to a sent request arrived.
 */
#define LEV_EVENT_RESPONSE_RECEIVED 10

/**
 * A sent request timed out without a response.
 */
#define LEV_EVENT_REQUEST_TIMEOUT 11

/**
 * An incoming resource was advertised (accept or reject it).
 */
#define LEV_EVENT_RESOURCE_ADVERTISED 12

/**
 * A resource transfer started.
 */
#define LEV_EVENT_RESOURCE_STARTED 13

/**
 * Resource transfer progress (`lev_event_progress`).
 */
#define LEV_EVENT_RESOURCE_PROGRESS 14

/**
 * A resource transfer completed (receiver gets data and metadata).
 */
#define LEV_EVENT_RESOURCE_COMPLETED 15

/**
 * A resource transfer failed.
 */
#define LEV_EVENT_RESOURCE_FAILED 16

/**
 * The peer proved an identity on a link; the 16-byte identity hash is the
 * event payload (`lev_event_data`), and `lev_link_remote_identity` returns it.
 */
#define LEV_EVENT_LINK_IDENTIFIED 17

/**
 * A reliable, sequenced message arrived on a link's channel (the peer used
 * the channel, as `lev_link_send` does). Distinct from `LEV_EVENT_LINK_DATA`,
 * which is a raw unsequenced link packet. Carries a message type and a
 * sequence number via `lev_event_msgtype` and `lev_event_sequence`.
 */
#define LEV_EVENT_LINK_MESSAGE 18

/**
 * A single packet arrived at a destination with the App proof strategy; the
 * app may call `lev_send_proof`. `dest_hash` is the destination, the data
 * payload is the 32-byte packet hash, and `lev_event_interface_id` reads the
 * interface the packet arrived on.
 */
#define LEV_EVENT_PACKET_PROOF_REQUESTED 19

/**
 * Data arrived on a link whose destination has the App proof strategy. The
 * `link_id` is set and the data payload is the 32-byte packet hash.
 */
#define LEV_EVENT_LINK_PROOF_REQUESTED 20

/**
 * A delivery proof confirmed a packet we sent on a link (PROVE_ALL). The
 * `link_id` is set and the data payload is the 32-byte packet hash.
 */
#define LEV_EVENT_LINK_DELIVERY_CONFIRMED 21

/**
 * A link went inactive past its keepalive deadline; `link_id` is set. The link
 * is not closed yet (see `LEV_EVENT_LINK_RECOVERED` and `LEV_EVENT_LINK_CLOSED`).
 */
#define LEV_EVENT_LINK_STALE 22

/**
 * A stale link resumed carrying traffic; `link_id` is set.
 */
#define LEV_EVENT_LINK_RECOVERED 23

/**
 * A known path to a destination expired; `dest_hash` is set.
 */
#define LEV_EVENT_PATH_LOST 24

/**
 * A delivery proof confirmed a single packet we sent; the data payload is the
 * 16-byte packet hash (as returned by `lev_send_datagram`).
 */
#define LEV_EVENT_PACKET_DELIVERY_CONFIRMED 25

/**
 * Delivery of a single packet we sent failed; the data payload is the 16-byte
 * packet hash and `lev_event_delivery_error` says why.
 */
#define LEV_EVENT_DELIVERY_FAILED 26

/**
 * No delivery proof arrived for a packet we sent on a link before its
 * RTT-derived receipt deadline expired. The `link_id` is set and the data
 * payload is the 32-byte packet hash (the failure half of
 * `LEV_EVENT_LINK_DELIVERY_CONFIRMED`).
 */
#define LEV_EVENT_LINK_DELIVERY_FAILED 27

/**
 * The local side or the peer closed the link deliberately. Reconnect freely.
 */
#define LEV_CLOSE_NORMAL 0

/**
 * The link handshake did not complete in time: the peer may be unreachable or
 * the path stale. Re-resolve the path before retrying.
 */
#define LEV_CLOSE_TIMEOUT 1

/**
 * A proof on the link did not verify. Retrying the same link gains nothing.
 */
#define LEV_CLOSE_INVALID_PROOF 2

/**
 * The peer closed the link. Reconnect when there is something to send.
 */
#define LEV_CLOSE_PEER_CLOSED 3

/**
 * The link went inactive past its keepalive deadline and was torn down.
 * Reconnect; a keepalive or traffic would have kept it alive.
 */
#define LEV_CLOSE_STALE 4

/**
 * A channel message could not be delivered after the maximum retries. The link
 * was working, so a reconnect is reasonable, but the payload was lost.
 */
#define LEV_CLOSE_CHANNEL_EXHAUSTED 5

/**
 * The peer identified as a blackholed identity and the link was torn down.
 * **Do not retry**: every attempt will be torn down the same way.
 */
#define LEV_CLOSE_BLACKHOLED 6

/**
 * A close reason this ABI version has no constant for. The engine enum is
 * extensible; `event_projection_coverage` fails on a new variant that reaches
 * here, so this is a forward-compatibility floor and not a silent bucket.
 */
#define LEV_CLOSE_OTHER 255

/**
 * No proof arrived before the receipt expired. Re-send.
 */
#define LEV_DELIVERY_TIMEOUT 0

/**
 * The link carrying the packet failed. Re-send (on a fresh link).
 */
#define LEV_DELIVERY_LINK_FAILED 1

/**
 * A proof arrived and did not verify against the destination's identity. The
 * peer answered, so re-sending produces the same unverifiable proof: re-resolve
 * the destination's identity instead.
 */
#define LEV_DELIVERY_INVALID_PROOF 2

/**
 * A delivery error this ABI version has no constant for; see
 * [`LEV_CLOSE_OTHER`].
 */
#define LEV_DELIVERY_OTHER 255

/**
 * Length of a destination or identity hash, in bytes.
 */
#define LEV_ADDR_LEN 16

/**
 * Length of a combined key, public or private, in bytes. The layout is the
 * X25519 key in bytes 0..32 then the Ed25519 key in bytes 32..64.
 */
#define LEV_IDENTITY_KEY_LEN 64

/**
 * Length of the X25519 (encryption) half, bytes 0..32 of a combined key.
 */
#define LEV_X25519_KEY_LEN 32

/**
 * Length of the Ed25519 (signing) half, bytes 32..64 of a combined key. This
 * is the key a link needs; see `lev_connect_with_key`.
 */
#define LEV_SIGNING_KEY_LEN 32

/**
 * No logging (default).
 */
#define LEV_LOG_OFF 0

/**
 * Errors only.
 */
#define LEV_LOG_ERROR 1

/**
 * Warnings and above.
 */
#define LEV_LOG_WARN 2

/**
 * Info and above.
 */
#define LEV_LOG_INFO 3

/**
 * Debug and above.
 */
#define LEV_LOG_DEBUG 4

/**
 * Everything.
 */
#define LEV_LOG_TRACE 5

/**
 * Drop all requests.
 */
#define LEV_REQUEST_POLICY_ALLOW_NONE 0

/**
 * Allow requests from any identity.
 */
#define LEV_REQUEST_POLICY_ALLOW_ALL 1

/**
 * Allow only identities in `allow_identity_hashes`.
 */
#define LEV_REQUEST_POLICY_ALLOW_LIST 2

/**
 * Length of a resource hash, in bytes.
 */
#define LEV_RESOURCE_HASH_LEN 32

/**
 * Reject all incoming resources.
 */
#define LEV_RESOURCE_ACCEPT_NONE 0

/**
 * Accept all incoming resources automatically.
 */
#define LEV_RESOURCE_ACCEPT_ALL 1

/**
 * Advertise incoming resources to the app, which accepts or rejects.
 */
#define LEV_RESOURCE_ACCEPT_APP 2

/**
 * Opaque node configuration handle.
 *
 * `inner` is taken (set to `None`) by `lev_builder_build`; the caller still
 * owns and frees the now-empty handle.
 */
typedef struct lev_builder_t lev_builder_t;

/**
 * Opaque destination handle. `inner` is taken by
 * `lev_register_destination`; the caller still frees the empty shell.
 */
typedef struct lev_destination_t lev_destination_t;

/**
 * One projected event, fully self-owned (all payloads deep-copied out of the
 * `NodeEvent`), so it outlives the queue slot and is valid until
 * `lev_event_free`.
 */
typedef struct lev_event_t lev_event_t;

/**
 * Opaque identity handle.
 */
typedef struct lev_identity_t lev_identity_t;

/**
 * An owned, point-in-time snapshot of every interface. Take it with
 * `lev_interface_stats_snapshot`, read entries by index, and release it with
 * `lev_interface_stats_free`.
 */
typedef struct lev_interface_stats_t lev_interface_stats_t;

/**
 * Opaque link handle.
 */
typedef struct lev_link_t lev_link_t;

/**
 * An owned, point-in-time snapshot of the path table. Take it with
 * `lev_path_table_snapshot`, read entries by index, and release it with
 * `lev_path_table_free`. Because it is a frozen copy, reads never race with a
 * changing table.
 */
typedef struct lev_path_table_t lev_path_table_t;

/**
 * Opaque node handle: owns the hidden runtime, the engine node, and the event
 * bridge that drains engine events onto a pollable fd.
 */
typedef struct leviculum_t leviculum_t;

/**
 * Log sink callback: `(level, message, user)`. The message is a
 * NUL-terminated string owned by the library, valid only for the duration of
 * the call. The callback may run on any internal worker thread and must not
 * call back into any `lev_*` function (see design §5, §12). It must not unwind
 * or throw across the boundary; a panic/exception that escapes the callback is
 * caught and swallowed by the library, but the record is then lost. NULL
 * restores the stderr default.
 *
 * Nullable on purpose: `Option` is inlined into the typedef so cbindgen
 * renders it as a plain (nullable) C function pointer, not an opaque struct.
 * The `C-unwind` ABI lets the library contain a callback that unwinds (a C++
 * exception, or a Rust callback that panics) with `catch_unwind` instead of
 * the process aborting at a plain `extern "C"` boundary. A normal
 * non-unwinding C callback remains fully compatible.
 */
typedef void (*lev_log_callback)(int level, const char *message, void *user);

/**
 * Obtain a handle to an already-established inbound link (16-byte link id
 * from a `LEV_EVENT_LINK_ESTABLISHED` event whose `inbound` flag is set).
 *
 * Inbound links are auto-accepted and auto-proved by the stack (Python-RNS
 * parity): the establishment proof is already sent by the time the event
 * fires, so this no longer "accepts" anything. It synchronously mints a
 * writable handle for the live link; on success `*out` is that handle. To
 * decline inbound links, configure the destination not to accept them rather
 * than refraining from calling this. `timeout_ms` is retained for ABI
 * stability and is unused (the call does not block).
 */
int lev_accept_link(const struct leviculum_t *node,
                    const uint8_t *link_id,
                    int timeout_ms,
                    struct lev_link_t **out);

/**
 * Accept a resource advertised on a link (after a
 * `LEV_EVENT_RESOURCE_ADVERTISED` event under the AcceptApp strategy).
 */
int lev_accept_resource(const struct leviculum_t *node, const uint8_t *link_id, int timeout_ms);

/**
 * Announce a registered destination (16-byte hash) on all interfaces.
 *
 * `app_data`/`app_data_len` is optional application payload (pass NULL/0 for
 * none). Blocks up to `timeout_ms` (negative means forever).
 */
int lev_announce(const struct leviculum_t *node,
                 const uint8_t *dest_hash,
                 const uint8_t *app_data,
                 uintptr_t app_data_len,
                 int timeout_ms);

/**
 * Add an AutoInterface (IPv6 multicast LAN discovery) with defaults.
 */
int lev_builder_add_auto_interface(struct lev_builder_t *b);

/**
 * Add an RNode (LoRa) interface. `port` is the serial device path; the rest
 * are the required radio settings (frequency in Hz, bandwidth in Hz,
 * spreading factor, coding rate denominator, tx power in dBm). Returns
 * `LEV_ERR_INVALID_ARG` on a NULL port.
 */
int lev_builder_add_rnode(struct lev_builder_t *b,
                          const char *port,
                          uint64_t frequency,
                          uint32_t bandwidth,
                          uint8_t spreading_factor,
                          uint8_t coding_rate,
                          int8_t tx_power);

/**
 * Add a serial interface (KISS framing over a raw serial port). `port` is the
 * device path, `parity` is one of "N", "E", "O". Returns
 * `LEV_ERR_INVALID_ARG` on a NULL port or parity.
 */
int lev_builder_add_serial(struct lev_builder_t *b,
                           const char *port,
                           uint32_t speed,
                           uint8_t databits,
                           const char *parity,
                           uint8_t stopbits);

/**
 * Add a TCP client interface to a remote node (`addr` is `host:port`).
 */
int lev_builder_add_tcp_client(struct lev_builder_t *b, const char *addr);

/**
 * Add a TCP server interface listening on `addr` (`host:port`).
 */
int lev_builder_add_tcp_server(struct lev_builder_t *b, const char *addr);

/**
 * Add a UDP interface bound to `listen_addr`, forwarding to `forward_addr`.
 */
int lev_builder_add_udp(struct lev_builder_t *b, const char *listen_addr, const char *forward_addr);

/**
 * Build a node from the builder. The builder is emptied but not freed; the
 * caller still calls `lev_builder_free`. Returns NULL on failure.
 */
struct leviculum_t *lev_builder_build(struct lev_builder_t *b);

/**
 * Load interface and node configuration from an INI config file (the format
 * `rnsd`/`lnsd` use), bringing every interface type, including RNode and
 * serial, into the node.
 */
int lev_builder_config_file(struct lev_builder_t *b, const char *path);

/**
 * Connect to a running shared instance `name` instead of bringing up own
 * interfaces, routing everything through that daemon.
 */
int lev_builder_connect_shared_instance(struct lev_builder_t *b, const char *name);

/**
 * Enable (`1`) or disable (`0`) transport (relay and routing) mode.
 */
int lev_builder_enable_transport(struct lev_builder_t *b, int enabled);

/**
 * Set the event-queue capacities for the node's pollable event fd: the
 * lossless control plane and the droppable data plane. A value of 0 keeps the
 * current default for that plane.
 */
int lev_builder_event_capacity(struct lev_builder_t *b, uintptr_t control_cap, uintptr_t data_cap);

/**
 * Free a builder handle. `lev_builder_free(NULL)` is a no-op.
 */
void lev_builder_free(struct lev_builder_t *b);

/**
 * Use an explicit identity instead of generating one. The identity is cloned.
 */
int lev_builder_identity(struct lev_builder_t *b, const struct lev_identity_t *id);

/**
 * Override the link keepalive interval, in seconds, for every link this node
 * creates. The stale-link timeout scales with it (stale at keepalive*2). The
 * value is clamped to the protocol minimum. Useful for slow links; with a
 * short value, `LEV_EVENT_LINK_STALE`/`LINK_RECOVERED` become observable in
 * seconds. A value of 0 is treated as the protocol minimum.
 */
int lev_builder_link_keepalive(struct lev_builder_t *b, uint64_t secs);

/**
 * Create a new node builder. Returns NULL on failure.
 */
struct lev_builder_t *lev_builder_new(void);

/**
 * Run as a shared instance under `name`: expose the local IPC socket and the
 * RPC server so `rnstatus`/`rnpath`/`rnprobe` and other tools can use this
 * node's transport.
 */
int lev_builder_share_instance(struct lev_builder_t *b, const char *name);

/**
 * Set the storage directory (UTF-8 path).
 */
int lev_builder_storage_path(struct lev_builder_t *b, const char *path);

/**
 * Close a link gracefully (idempotent). Blocks up to `timeout_ms`.
 */
int lev_close_link(struct lev_link_t *link, int timeout_ms);

/**
 * Open a link to a destination (16-byte hash), resolving its signing key from
 * the identity cached from an announce. On success `*out` is the link handle.
 *
 * `LEV_ERR_UNKNOWN_DEST` if no identity is cached, `LEV_ERR_NO_PATH` if no path
 * is known (request one first; connect does not auto-request).
 */
int lev_connect(const struct leviculum_t *node,
                const uint8_t *dest_hash,
                int timeout_ms,
                struct lev_link_t **out);

/**
 * Open a link with an explicit Ed25519 signing key (32 bytes), for out-of-band
 * keys where no announce was seen. `LEV_ERR_NO_PATH` if no path is known.
 */
int lev_connect_with_key(const struct leviculum_t *node,
                         const uint8_t *dest_hash,
                         const uint8_t *signing_key,
                         int timeout_ms,
                         struct lev_link_t **out);

/**
 * Enable ratchets (forward secrecy) on a destination before it is registered.
 * `now_ms` is the current time in milliseconds (e.g. `clock_gettime`), used to
 * seed ratchet rotation. Call before `lev_register_destination`.
 * `LEV_ERR_INVALID_ARG` for an outbound destination or one already registered.
 */
int lev_destination_enable_ratchets(struct lev_destination_t *dest, uint64_t now_ms);

/**
 * Free a destination handle. `lev_destination_free(NULL)` is a no-op.
 */
void lev_destination_free(struct lev_destination_t *dest);

/**
 * Write the destination hash (16 bytes) into `buf`, read(2) style.
 * `LEV_ERR_INVALID_ARG` if the destination was already registered (consumed).
 */
int lev_destination_hash(const struct lev_destination_t *dest,
                         uint8_t *buf,
                         uintptr_t cap,
                         uintptr_t *out_len);

/**
 * Create a destination.
 *
 * `identity` may be NULL (required for some types, forbidden for PLAIN).
 * `aspects` is an array of `n_aspects` NUL-terminated UTF-8 strings.
 * Returns NULL on failure.
 */
struct lev_destination_t *lev_destination_new(const struct lev_identity_t *identity,
                                              int direction,
                                              int dest_type,
                                              const char *app_name,
                                              const char *const *aspects,
                                              uintptr_t n_aspects);

/**
 * Write the current 32-byte ratchet public key of a registered local
 * destination into `buf`, read(2) style. `LEV_ERR_INVALID_ARG` if the
 * destination is unknown or has no ratchets enabled.
 */
int lev_destination_ratchet_public(const struct leviculum_t *node,
                                   const uint8_t *dest_hash,
                                   uint8_t *buf,
                                   uintptr_t cap,
                                   uintptr_t *out_len);

/**
 * Choose whether an inbound destination accepts links when registered. The
 * default is `1` (accept), the auto-accept model (Python-RNS parity). Pass `0`
 * to keep the destination reachable for announces and packets while declining
 * inbound links (Codeberg #21). No effect on outbound destinations. Call
 * before `lev_register_destination`. `LEV_ERR_INVALID_ARG` if already
 * registered.
 */
int lev_destination_set_accepts_links(struct lev_destination_t *dest, int accepts);

/**
 * Set the delivery-proof strategy on a destination before it is registered:
 * `LEV_PROOF_NONE`, `LEV_PROOF_APP` (emit `LEV_EVENT_PACKET_PROOF_REQUESTED`
 * so the app calls `lev_send_proof`), or `LEV_PROOF_ALL` (auto-prove every
 * received packet). `LEV_ERR_INVALID_ARG` on a bad strategy or a registered
 * destination.
 */
int lev_destination_set_proof_strategy(struct lev_destination_t *dest, int strategy);

/**
 * Read why a `LEV_EVENT_LINK_CLOSED` event's link closed into `*out`, as one of
 * the `LEV_CLOSE_*` constants. `LEV_ERR_INVALID_ARG` for any other event type.
 *
 * The reason is behavioural, not cosmetic: `LEV_CLOSE_BLACKHOLED` must not be
 * retried at all, `LEV_CLOSE_TIMEOUT` wants the path re-resolved first, and
 * `LEV_CLOSE_NORMAL`/`_PEER_CLOSED` may be reconnected immediately.
 */
int lev_event_close_reason(const struct lev_event_t *ev, int *out);

/**
 * Write the event's primary payload into `buf`, read(2) style. The payload may
 * be empty (sets `*out_len` to 0).
 */
int lev_event_data(const struct lev_event_t *ev, uint8_t *buf, uintptr_t cap, uintptr_t *out_len);

/**
 * Read the original uncompressed data size of a resource, in bytes, into
 * `*out`. Set on the same events as `lev_event_transfer_size`; this is the size
 * the assembled payload will have, which is what an accept/reject decision and
 * a receive buffer are sized against. `LEV_ERR_INVALID_ARG` for any other event
 * type.
 */
int lev_event_data_size(const struct lev_event_t *ev, uint64_t *out);

/**
 * Read why a `LEV_EVENT_DELIVERY_FAILED` event's packet was not delivered into
 * `*out`, as one of the `LEV_DELIVERY_*` constants. `LEV_ERR_INVALID_ARG` for
 * any other event type.
 *
 * `LEV_DELIVERY_TIMEOUT` and `_LINK_FAILED` mean re-send;
 * `LEV_DELIVERY_INVALID_PROOF` means the peer answered with a proof that did
 * not verify, so re-sending produces the same result.
 */
int lev_event_delivery_error(const struct lev_event_t *ev, int *out);

/**
 * Write the event's destination hash (16 bytes) into `buf`, read(2) style.
 * `LEV_ERR_INVALID_ARG` if the event has no destination hash.
 */
int lev_event_dest_hash(const struct lev_event_t *ev,
                        uint8_t *buf,
                        uintptr_t cap,
                        uintptr_t *out_len);

/**
 * Read the dropped-event count of a `LEV_EVENT_CONTROL_OVERFLOW` event.
 * `LEV_ERR_INVALID_ARG` for any other event type.
 */
int lev_event_dropped_count(const struct lev_event_t *ev, uint64_t *out);

/**
 * Return the readable event fd to add to the app's `poll`/`epoll`/`select`
 * loop. The fd is owned by the library and closed by `lev_free`; the app must
 * never close it. Returns a negative error code on a NULL node.
 */
int lev_event_fd(const struct leviculum_t *node);

/**
 * Free an event handle returned by `lev_next_event`/`lev_wait_event`.
 * `lev_event_free(NULL)` is a no-op.
 */
void lev_event_free(struct lev_event_t *ev);

/**
 * Read the node-assigned id of the interface an event arrived on into `*out`.
 *
 * Set on `LEV_EVENT_ANNOUNCE_RECEIVED`, `LEV_EVENT_PATH_FOUND` and
 * `LEV_EVENT_PACKET_RECEIVED`; `LEV_ERR_INVALID_ARG` on any other event type.
 *
 * This is an *id*, not a position in the interface snapshot: resolve it to an
 * interface by walking `lev_interface_stats_snapshot` and comparing
 * `lev_interface_stats_id`, then read the name with
 * `lev_interface_stats_name`. It is the same numbering `lev_path_table_entry`
 * reports as `interface_index`, so a path and the announce that created it can
 * be attributed to one interface.
 */
int lev_event_interface_id(const struct lev_event_t *ev, uint64_t *out);

/**
 * Whether a resource event is for a transfer this node is *sending*. Returns 1
 * on the sender side of a `LEV_EVENT_RESOURCE_PROGRESS`/`_COMPLETED`/`_FAILED`
 * event, 0 on the receiver side.
 *
 * `LEV_EVENT_RESOURCE_STARTED` is absent from that list because the engine
 * emits it on the receiver only (`is_sender: false` at both push sites), so 0
 * there is the truth and not a gap in the projection.
 *
 * One non-resource event also sets this flag: `LEV_EVENT_LINK_ESTABLISHED`
 * returns 1 for a link this node initiated and 0 for an inbound one, which is
 * that event's documented inbound indicator (see the constant). Everything
 * else, and a NULL pointer, returns 0.
 *
 * A sender's `LEV_EVENT_RESOURCE_COMPLETED` is the signal that an outgoing
 * transfer finished (its data payload is empty); a receiver's carries the
 * assembled data. Use this to tell the two apart on a node that both sends and
 * receives resources.
 */
int lev_event_is_sender(const struct lev_event_t *ev);

/**
 * Write the event's link id (16 bytes) into `buf`, read(2) style.
 * `LEV_ERR_INVALID_ARG` if the event has no link id.
 */
int lev_event_link_id(const struct lev_event_t *ev,
                      uint8_t *buf,
                      uintptr_t cap,
                      uintptr_t *out_len);

/**
 * Write the event's metadata (msgpack bytes) into `buf`, read(2) style.
 * `LEV_ERR_INVALID_ARG` if the event has no metadata.
 */
int lev_event_metadata(const struct lev_event_t *ev,
                       uint8_t *buf,
                       uintptr_t cap,
                       uintptr_t *out_len);

/**
 * Read the message type of a `LEV_EVENT_LINK_MESSAGE` event into `*out`. The
 * type identifies the channel message kind on the wire (0 is the raw bytes
 * message that `lev_link_send` uses and that Python's `RawBytesMessage`
 * carries). `LEV_ERR_INVALID_ARG` for any other event type.
 */
int lev_event_msgtype(const struct lev_event_t *ev, uint16_t *out);

/**
 * Write the event's request path into `buf` as UTF-8 bytes (not
 * NUL-terminated), read(2) style. `LEV_ERR_INVALID_ARG` if the event has no
 * path.
 */
int lev_event_path(const struct lev_event_t *ev, uint8_t *buf, uintptr_t cap, uintptr_t *out_len);

/**
 * Write the transfer progress (0.0..1.0) of a `LEV_EVENT_RESOURCE_PROGRESS`
 * event into `*out`. `LEV_ERR_INVALID_ARG` for any other event type.
 */
int lev_event_progress(const struct lev_event_t *ev, double *out);

/**
 * Write the event's request id (16 bytes) into `buf`, read(2) style.
 * `LEV_ERR_INVALID_ARG` if the event has no request id.
 */
int lev_event_request_id(const struct lev_event_t *ev,
                         uint8_t *buf,
                         uintptr_t cap,
                         uintptr_t *out_len);

/**
 * Write the event's resource hash (32 bytes) into `buf`, read(2) style.
 * `LEV_ERR_INVALID_ARG` if the event has no resource hash.
 */
int lev_event_resource_hash(const struct lev_event_t *ev,
                            uint8_t *buf,
                            uintptr_t cap,
                            uintptr_t *out_len);

/**
 * Read the 1-based segment index of a `LEV_EVENT_RESOURCE_COMPLETED` event into
 * `*out`. `LEV_ERR_INVALID_ARG` for any other event type.
 *
 * A multi-segment resource fires one completion per segment, all carrying the
 * same `resource_hash`, so this and `lev_event_total_segments` are how a C
 * receiver orders the chunks and recognises the last one
 * (`segment_index == total_segments`). Metadata is present on segment 1 only.
 */
int lev_event_segment_index(const struct lev_event_t *ev, uint32_t *out);

/**
 * Read the sequence number of a `LEV_EVENT_LINK_MESSAGE` event into `*out`.
 * The channel assigns sequence numbers in send order for reliable, ordered
 * delivery. `LEV_ERR_INVALID_ARG` for any other event type.
 */
int lev_event_sequence(const struct lev_event_t *ev, uint16_t *out);

/**
 * Read the total number of segments of a `LEV_EVENT_RESOURCE_COMPLETED` event's
 * transfer into `*out`. 1 for a single-segment resource.
 * `LEV_ERR_INVALID_ARG` for any other event type. See
 * `lev_event_segment_index`.
 */
int lev_event_total_segments(const struct lev_event_t *ev, uint32_t *out);

/**
 * Read the total encrypted transfer size of a resource, in bytes, into `*out`.
 *
 * Set on `LEV_EVENT_RESOURCE_ADVERTISED` (so an app under the AcceptApp
 * strategy can decide whether to accept it) and on
 * `LEV_EVENT_RESOURCE_PROGRESS` (the only place an auto-accepting receiver sees
 * it, since no advertisement is surfaced there). `LEV_ERR_INVALID_ARG` for any
 * other event type.
 */
int lev_event_transfer_size(const struct lev_event_t *ev, uint64_t *out);

/**
 * The event's type, one of the `LEV_EVENT_*` constants. Returns
 * `LEV_EVENT_OTHER` (0) on a NULL pointer, which is indistinguishable from a
 * real `LEV_EVENT_OTHER` event; callers that may pass NULL should null-check
 * the handle first (`lev_next_event`/`lev_wait_event` already yield non-NULL
 * handles, so this only matters for hand-constructed pointers).
 */
int lev_event_type(const struct lev_event_t *ev);

/**
 * Free a node handle, stopping it gracefully first if still running.
 * `lev_free(NULL)` is a no-op.
 */
void lev_free(struct leviculum_t *node);

/**
 * Return 1 if a path to the destination (16-byte hash) is known, else 0
 * (negative on a NULL argument).
 */
int lev_has_path(const struct leviculum_t *node, const uint8_t *dest_hash);

/**
 * Decode hex (`hex_len` bytes, even) into `buf`, read(2) style. Writes
 * `hex_len / 2` bytes; `*out_len` is set to the required size.
 * `LEV_ERR_INVALID_ARG` on an odd length or a non-hex digit.
 */
int lev_hex_decode(const uint8_t *hex,
                   uintptr_t hex_len,
                   uint8_t *buf,
                   uintptr_t cap,
                   uintptr_t *out_len);

/**
 * Encode `data` as lowercase hex into `buf`, read(2) style. Writes `2 * len`
 * bytes (not NUL-terminated); `*out_len` is set to the required size.
 */
int lev_hex_encode(const uint8_t *data,
                   uintptr_t len,
                   uint8_t *buf,
                   uintptr_t cap,
                   uintptr_t *out_len);

/**
 * Write the hop count to a destination into `*out`. `LEV_ERR_NO_PATH` if no
 * path is known.
 */
int lev_hops_to(const struct leviculum_t *node, const uint8_t *dest_hash, uint8_t *out);

/**
 * Decrypt `ciphertext` with the identity's X25519 private key. Writes the
 * plaintext read(2) style (NULL `buf` queries the length). `LEV_ERR_CRYPTO` if
 * the identity has no private key or the ciphertext fails to authenticate.
 */
int lev_identity_decrypt(const struct lev_identity_t *id,
                         const uint8_t *ciphertext,
                         uintptr_t ciphertext_len,
                         uint8_t *buf,
                         uintptr_t cap,
                         uintptr_t *out_len);

/**
 * Encrypt `plaintext` to the identity's public key (X25519 + AES, the
 * Reticulum scheme). Writes the ciphertext read(2) style (NULL `buf` queries
 * the length). Encryption is randomised, so a length query and the real call
 * produce different bytes of the same length; size from the query, then call
 * again with a buffer.
 */
int lev_identity_encrypt(const struct lev_identity_t *id,
                         const uint8_t *plaintext,
                         uintptr_t plaintext_len,
                         uint8_t *buf,
                         uintptr_t cap,
                         uintptr_t *out_len);

/**
 * Free an identity handle. `lev_identity_free(NULL)` is a no-op.
 */
void lev_identity_free(struct lev_identity_t *id);

/**
 * Load a full identity from its 64-byte combined private key.
 *
 * `len` must equal `LEV_IDENTITY_KEY_LEN`. Returns NULL on failure.
 */
struct lev_identity_t *lev_identity_from_private_key(const uint8_t *key, uintptr_t len);

/**
 * Load a public-only identity from its 64-byte combined public key.
 *
 * `len` must equal `LEV_IDENTITY_KEY_LEN`. Returns NULL on failure.
 */
struct lev_identity_t *lev_identity_from_public_key(const uint8_t *key, uintptr_t len);

/**
 * Generate a new random identity. Returns NULL on failure.
 */
struct lev_identity_t *lev_identity_generate(void);

/**
 * Return 1 if the identity holds private keys, 0 otherwise (also 0 on NULL).
 */
int lev_identity_has_private_keys(const struct lev_identity_t *id);

/**
 * Write the identity hash (16 bytes) into `buf`, read(2) style.
 */
int lev_identity_hash(const struct lev_identity_t *id,
                      uint8_t *buf,
                      uintptr_t cap,
                      uintptr_t *out_len);

/**
 * Write the node's own identity hash (16 bytes) into `buf`, read(2) style.
 */
int lev_identity_hash_self(const struct leviculum_t *node,
                           uint8_t *buf,
                           uintptr_t cap,
                           uintptr_t *out_len);

/**
 * Load a full identity from a raw 64-byte private key file (Python-compatible
 * format). Returns NULL on failure (missing file, wrong size, or bad keys).
 */
struct lev_identity_t *lev_identity_load_file(const char *path);

/**
 * Write the combined private key (64 bytes) into `buf`, read(2) style.
 *
 * Returns `LEV_ERR_CRYPTO` if the identity is public-only.
 */
int lev_identity_private_key(const struct lev_identity_t *id,
                             uint8_t *buf,
                             uintptr_t cap,
                             uintptr_t *out_len);

/**
 * Write the combined public key (64 bytes) into `buf`, read(2) style.
 */
int lev_identity_public_key(const struct lev_identity_t *id,
                            uint8_t *buf,
                            uintptr_t cap,
                            uintptr_t *out_len);

/**
 * Save the identity's private key to `path` as raw 64 bytes, the format Python
 * Reticulum uses (`rnsd` and friends read it). Requires private keys.
 * Written atomically (temp file then rename).
 */
int lev_identity_save_file(const struct lev_identity_t *id, const char *path);

/**
 * Sign `msg` with the identity's Ed25519 private key. Writes the 64-byte
 * signature read(2) style (NULL `buf` queries the length). `LEV_ERR_CRYPTO`
 * if the identity has no private key.
 */
int lev_identity_sign(const struct lev_identity_t *id,
                      const uint8_t *msg,
                      uintptr_t msg_len,
                      uint8_t *buf,
                      uintptr_t cap,
                      uintptr_t *out_len);

/**
 * Verify `sig` over `msg` against the identity's Ed25519 public key. Returns 1
 * if valid, 0 if the signature does not match, and a negative `LEV_ERR_*` on a
 * NULL argument or a malformed signature.
 */
int lev_identity_verify(const struct lev_identity_t *id,
                        const uint8_t *msg,
                        uintptr_t msg_len,
                        const uint8_t *sig,
                        uintptr_t sig_len);

/**
 * Perform one-time process setup (logging subscriber, panic hook).
 *
 * Idempotent and safe to call from multiple threads. Optional: other entry
 * points run it lazily, but call it explicitly to configure logging before
 * the first node is built.
 */
int lev_init(void);

/**
 * Number of interfaces in a snapshot, or 0 on NULL.
 */
int lev_interface_stats_count(const struct lev_interface_stats_t *table);

/**
 * Read the scalar fields of interface `index` into the out-parameters: online
 * (1/0), is_local_client (1/0), and the byte counters. Any out-pointer may be
 * NULL to skip it. `LEV_ERR_INVALID_ARG` if `index` is out of range. Read the
 * name with `lev_interface_stats_name`.
 */
int lev_interface_stats_entry(const struct lev_interface_stats_t *table,
                              uintptr_t index,
                              int *online,
                              int *is_local_client,
                              uint64_t *rx_bytes,
                              uint64_t *tx_bytes);

/**
 * Release an interface-stats snapshot. `lev_interface_stats_free(NULL)` is a
 * no-op.
 */
void lev_interface_stats_free(struct lev_interface_stats_t *table);

/**
 * Write the node-assigned id of interface `index` into `*out_id`.
 *
 * The snapshot is indexed by *position*, which is not an interface's identity:
 * the node numbers interfaces as they are registered and never renumbers, so a
 * removed interface leaves a gap and every later position is off by it. This is
 * the accessor that resolves an id to an entry — the ids the rest of the API
 * hands out (`interface_index` from `lev_path_table_entry`,
 * `lev_event_interface_id` on an announce, path or packet event) name *this*
 * value, not a position. Walk the snapshot comparing it, then read the name
 * with `lev_interface_stats_name`.
 *
 * `LEV_ERR_NULL_PTR` if `table` or `out_id` is NULL, `LEV_ERR_INVALID_ARG` if
 * `index` is out of range.
 */
int lev_interface_stats_id(const struct lev_interface_stats_t *table,
                           uintptr_t index,
                           uint64_t *out_id);

/**
 * Write the name of interface `index` into `buf`, read(2) style (the name is
 * variable length; a NULL `buf` queries the length). `LEV_ERR_INVALID_ARG` if
 * `index` is out of range.
 */
int lev_interface_stats_name(const struct lev_interface_stats_t *table,
                             uintptr_t index,
                             uint8_t *buf,
                             uintptr_t cap,
                             uintptr_t *out_len);

/**
 * Capture a snapshot of the node's interfaces (name, online status, byte
 * counters). Returns an owned handle (free with `lev_interface_stats_free`),
 * or NULL on a NULL node.
 */
struct lev_interface_stats_t *lev_interface_stats_snapshot(const struct leviculum_t *node);

/**
 * Return 1 if the node event loop is running, 0 otherwise (also 0 on NULL).
 */
int lev_is_running(const struct leviculum_t *node);

/**
 * Return the thread-local detail string for the most recent failing call on
 * this thread, or NULL if there is none.
 *
 * The string is owned by the library and valid until the next failing call on
 * the same thread. The caller must not free it.
 */
const char *lev_last_error(void);

/**
 * Free a link handle, closing it first if still open. `lev_link_free(NULL)` is
 * a no-op.
 */
void lev_link_free(struct lev_link_t *link);

/**
 * Write the link id (16 bytes) into `buf`, read(2) style.
 */
int lev_link_id(const struct lev_link_t *link, uint8_t *buf, uintptr_t cap, uintptr_t *out_len);

/**
 * Prove an identity to the peer on a link (16-byte link id). The peer sees a
 * `LEV_EVENT_LINK_IDENTIFIED` event and can read it via
 * `lev_link_remote_identity`. Blocks up to `timeout_ms`.
 */
int lev_link_identify(const struct leviculum_t *node,
                      const uint8_t *link_id,
                      const struct lev_identity_t *identity,
                      int timeout_ms);

/**
 * Return 1 if the link is closed, 0 otherwise (also 0 on NULL).
 */
int lev_link_is_closed(const struct lev_link_t *link);

/**
 * Return the peer's identity on a link (16-byte link id) as a new identity
 * handle the caller frees, or NULL if the peer has not identified.
 */
struct lev_identity_t *lev_link_remote_identity(const struct leviculum_t *node,
                                                const uint8_t *link_id);

/**
 * Send data on a link, blocking up to `timeout_ms`. `LEV_ERR_AGAIN` is not
 * returned here; `lev_link_send` retries backpressure internally up to the
 * deadline, then `LEV_ERR_TIMEOUT`.
 */
int lev_link_send(const struct lev_link_t *link,
                  const uint8_t *data,
                  uintptr_t len,
                  int timeout_ms);

/**
 * Read the per-link delivery telemetry (leviculum#35) for the link with the
 * given 16-byte id into the provided out-parameters. Any out-pointer may be
 * NULL to skip that value. Counters are cumulative; sample periodically and
 * difference consecutive readings.
 *
 * - `out_bytes_delivered` — proof-confirmed bytes (channel envelopes plus
 *   completed outgoing resources), the delivery-rate numerator.
 * - `out_srtt_ms` / `out_rttvar_ms` — RFC 6298 smoothed delivery RTT and
 *   variance in milliseconds; `-1.0` until the first Karn-valid sample.
 * - `out_min_rtt_ms` — floor of Karn-valid delivery RTT samples in
 *   milliseconds; `-1` until the first sample.
 * - `out_rtt_ms` — handshake RTT from link establishment in milliseconds;
 *   `-1` when not measured.
 * - `out_busy_rejections` / `out_pacing_rejections` /
 *   `out_iface_pacing_rejections` — sends rejected by a full channel window,
 *   the link pacer, and the interface airtime gate respectively: a non-zero
 *   interval delta marks the interval congestion-limited rather than
 *   app-limited.
 * - `out_tx_ring_size`, `out_window`, `out_window_max`,
 *   `out_pacing_interval_ms` — the channel flow-control state.
 *
 * Returns `LEV_OK`; `LEV_ERR_NULL_PTR` on a NULL node or link id;
 * `LEV_ERR_LINK` when no link with that id exists.
 */
int lev_link_stats(const struct leviculum_t *node,
                   const uint8_t *link_id,
                   uint64_t *out_bytes_delivered,
                   double *out_srtt_ms,
                   double *out_rttvar_ms,
                   int64_t *out_min_rtt_ms,
                   int64_t *out_rtt_ms,
                   uint64_t *out_busy_rejections,
                   uint64_t *out_pacing_rejections,
                   uint64_t *out_iface_pacing_rejections,
                   uint64_t *out_tx_ring_size,
                   uint64_t *out_window,
                   uint64_t *out_window_max,
                   uint64_t *out_pacing_interval_ms);

/**
 * Try to send without blocking. `LEV_ERR_AGAIN` on backpressure (retry later).
 */
int lev_link_try_send(const struct lev_link_t *link, const uint8_t *data, uintptr_t len);

/**
 * Set the log sink callback, or pass `NULL` to restore the stderr default.
 * `user` is passed back to the callback unchanged.
 */
int lev_log_set_callback(lev_log_callback cb, void *user);

/**
 * Set the global log level. One of the `LEV_LOG_*` constants.
 */
int lev_log_set_level(int level);

/**
 * Dequeue the next event without blocking. On success `*out` is the event
 * handle (free it with `lev_event_free`) or NULL when the queue is empty.
 */
int lev_next_event(struct leviculum_t *node, struct lev_event_t **out);

/**
 * Number of entries in a path-table snapshot, or 0 on NULL.
 */
int lev_path_table_count(const struct lev_path_table_t *table);

/**
 * Read one entry of a path-table snapshot by index into the out-parameters.
 * `dest_hash` and `next_hop`, if non-NULL, must be at least `LEV_ADDR_LEN`
 * (16) bytes; `has_next_hop` reports whether `next_hop` was written (a relayed
 * path has one, a direct path does not). Any out-pointer may be NULL to skip
 * it. `LEV_ERR_INVALID_ARG` if `index` is out of range.
 */
int lev_path_table_entry(const struct lev_path_table_t *table,
                         uintptr_t index,
                         uint8_t *dest_hash,
                         uint8_t *hops,
                         uint8_t *next_hop,
                         int *has_next_hop,
                         uint64_t *interface_index,
                         uint64_t *expires_ms);

/**
 * Release a path-table snapshot. `lev_path_table_free(NULL)` is a no-op.
 */
void lev_path_table_free(struct lev_path_table_t *table);

/**
 * Capture a snapshot of the node's path table. Returns an owned handle (free
 * with `lev_path_table_free`), or NULL on a NULL node.
 */
struct lev_path_table_t *lev_path_table_snapshot(const struct leviculum_t *node);

/**
 * Register a destination on the node so it can be announced and can accept
 * links or packets. Consumes the destination (the handle is emptied; still
 * free it). Inbound links are accepted unless
 * `lev_destination_set_accepts_links(dest, 0)` was called first.
 * `LEV_ERR_INVALID_ARG` if already registered.
 */
int lev_register_destination(const struct leviculum_t *node, struct lev_destination_t *dest);

/**
 * Register a request handler for `path` on a local destination (16-byte hash).
 *
 * `allow_identity_hashes` is `n_ids * 16` bytes of identity hashes, read only
 * for `LEV_REQUEST_POLICY_ALLOW_LIST`. Registering overwrites any previous
 * handler for the same destination and path; there is no unregister.
 */
int lev_register_request_handler(const struct leviculum_t *node,
                                 const uint8_t *dest_hash,
                                 const char *path,
                                 int policy,
                                 const uint8_t *allow_identity_hashes,
                                 uintptr_t n_ids);

/**
 * Reject a resource advertised on a link.
 */
int lev_reject_resource(const struct leviculum_t *node, const uint8_t *link_id, int timeout_ms);

/**
 * Request a path to a destination. The result arrives as an event and
 * `lev_has_path` then returns 1. Blocks up to `timeout_ms`.
 */
int lev_request_path(const struct leviculum_t *node, const uint8_t *dest_hash, int timeout_ms);

/**
 * Send one unreliable datagram (single packet) to a destination (16-byte
 * hash), writing the 16-byte packet hash into `out_hash`. A path must already
 * be known (`LEV_ERR_NO_PATH` otherwise). Blocks up to `timeout_ms`.
 */
int lev_send_datagram(const struct leviculum_t *node,
                      const uint8_t *dest_hash,
                      const uint8_t *data,
                      uintptr_t data_len,
                      uint8_t *out_hash,
                      int timeout_ms);

/**
 * Send a delivery proof for a received packet, in response to a
 * `LEV_EVENT_PACKET_PROOF_REQUESTED` event (App strategy). `dest_hash` and
 * `packet_hash` (32 bytes) come from the event.
 */
int lev_send_proof(const struct leviculum_t *node,
                   const uint8_t *dest_hash,
                   const uint8_t *packet_hash,
                   int timeout_ms);

/**
 * Send a request on an established link (16-byte link id) to `path`, writing
 * the 16-byte request id into `out_request_id`. `data`/`data_len` is the
 * msgpack-encoded payload (NULL/0 for none). `response_timeout_ms` is the
 * request-response deadline (negative for none); the response or a timeout
 * arrives as an event.
 */
int lev_send_request(const struct leviculum_t *node,
                     const uint8_t *link_id,
                     const char *path,
                     const uint8_t *data,
                     uintptr_t data_len,
                     int response_timeout_ms,
                     uint8_t *out_request_id);

/**
 * Send a resource over an established link (16-byte link id), writing the
 * 32-byte resource hash into `out_hash`. `metadata`, if present, must be
 * msgpack-encoded. `auto_compress` is a boolean (0 or 1). Blocks up to
 * `timeout_ms` for the initial dispatch; progress and completion are events.
 */
int lev_send_resource(const struct leviculum_t *node,
                      const uint8_t *link_id,
                      const uint8_t *data,
                      uintptr_t data_len,
                      const uint8_t *metadata,
                      uintptr_t metadata_len,
                      int auto_compress,
                      uint8_t *out_hash,
                      int timeout_ms);

/**
 * Send a response to a received request (link id and request id, each 16
 * bytes). `data`/`data_len` must be one valid msgpack-encoded value. Blocks up
 * to `timeout_ms`.
 */
int lev_send_response(const struct leviculum_t *node,
                      const uint8_t *link_id,
                      const uint8_t *request_id,
                      const uint8_t *data,
                      uintptr_t data_len,
                      int timeout_ms);

/**
 * Send a response resource to a received request (link id and request id, each 16
 * bytes). Blocks up to .
 */
int lev_send_response_resource(const struct leviculum_t *node,
                               const uint8_t *link_id,
                               const uint8_t *request_id,
                               const uint8_t *data,
                               uintptr_t data_len,
                               int timeout_ms);

/**
 * Set the acceptance strategy for incoming resources on a link.
 */
int lev_set_resource_strategy(const struct leviculum_t *node, const uint8_t *link_id, int strategy);

/**
 * Start the node: spawn the event loop and bring up interfaces.
 */
int lev_start(struct leviculum_t *node);

/**
 * Stop the node, persist state, and tear down the event loop.
 */
int lev_stop(struct leviculum_t *node);

/**
 * Return a static, never-freed message for an error code.
 *
 * Safe to call at any time. The returned pointer must not be freed.
 */
const char *lev_strerror(int code);

/**
 * Write the bound address (`ip:port`) of the node's TCP server listener
 * number `index` (in start order) into `buf`, read(2) style (a NULL `buf`
 * queries the length). A server added with port 0 reports the
 * kernel-assigned port here once the node has started — bind `:0` and read
 * the chosen port back instead of probing a free port up front and racing
 * every co-tenant for the re-bind (Codeberg #221). `LEV_ERR_INVALID_ARG` if
 * `index` is out of range (including "before start": the listeners bind
 * during `lev_start`).
 */
int lev_tcp_listen_addr(const struct leviculum_t *node,
                        uintptr_t index,
                        uint8_t *buf,
                        uintptr_t cap,
                        uintptr_t *out_len);

/**
 * Read the transport counters into the provided out-parameters: packets sent,
 * received, forwarded, announces processed, packets dropped, and the current
 * path-table size. Any out-pointer may be NULL to skip that counter. Returns
 * `LEV_OK`, or `LEV_ERR_NULL_PTR` if `node` is NULL.
 */
int lev_transport_stats(const struct leviculum_t *node,
                        uint64_t *out_packets_sent,
                        uint64_t *out_packets_received,
                        uint64_t *out_packets_forwarded,
                        uint64_t *out_announces_processed,
                        uint64_t *out_packets_dropped,
                        uint64_t *out_path_count);

/**
 * Return the library version as `(major << 16) | (minor << 8) | patch`.
 */
uint32_t lev_version_number(void);

/**
 * Return the library version string, for example `"0.7.0"`.
 *
 * Static storage, never freed.
 */
const char *lev_version_string(void);

/**
 * Block up to `timeout_ms` for the next event (negative means forever). On
 * success `*out` is the event handle, or NULL if the timeout elapsed first.
 *
 * Single-consumer: do not call concurrently with `lev_next_event` on the same
 * node.
 */
int lev_wait_event(struct leviculum_t *node, struct lev_event_t **out, int timeout_ms);

#endif  /* LEVICULUM_H */
