//! Verifies leviculum-core against every vector in the corpus.
//!
//! The corpus is generated by the Python reference implementation, which is
//! normative. A failure here is a wire incompatibility in leviculum-core,
//! never a bad vector: report it, do not regenerate around it.

use std::collections::BTreeSet;

use leviculum_core::crypto::{
    aes256_cbc_decrypt, aes256_cbc_encrypt, decrypt_token, encrypt_token, hmac_sha256, verify_hmac,
};
use leviculum_core::packet::packet_hash;
use leviculum_core::{Destination, DestinationType, Direction, Identity};
use vectors_verify::{
    load, skip_without_corpus, vectors_dir, AesCbcVector, DestinationVector, HmacVector,
    PacketVector, TokenVector,
};

fn unhex(field: &str, vector: &str, value: &str) -> Vec<u8> {
    hex::decode(value).unwrap_or_else(|e| panic!("bad hex in {vector}.{field}: {e}"))
}

#[test]
fn corpus_files_all_covered() {
    if skip_without_corpus("corpus_files_all_covered") {
        return;
    }
    // Every JSON file in the corpus must be verified by a test in this file;
    // a new category showing up unreferenced must fail, not pass silently.
    let mut found = BTreeSet::new();
    for entry in std::fs::read_dir(vectors_dir()).expect("corpus directory") {
        let name = entry.expect("dir entry").file_name();
        let name = name.to_string_lossy().into_owned();
        if name.ends_with(".json") {
            found.insert(name);
        }
    }
    let expected: BTreeSet<String> = [
        "hmac_sha256.json",
        "aes256_cbc.json",
        "token.json",
        "destination_hash.json",
        "packet_hash.json",
    ]
    .into_iter()
    .map(String::from)
    .collect();
    assert_eq!(found, expected, "corpus files and verification out of sync");
}

#[test]
fn hmac_sha256_vectors() {
    if skip_without_corpus("hmac_sha256_vectors") {
        return;
    }
    for v in load::<HmacVector>("hmac_sha256.json").vectors {
        let key = unhex("key", &v.name, &v.key);
        let data = unhex("data", &v.name, &v.data);
        let mac = unhex("mac", &v.name, &v.mac);

        assert_eq!(hmac_sha256(&key, &data).as_slice(), mac, "{}", v.name);
        assert!(verify_hmac(&key, &data, &mac), "{}", v.name);

        let mut tampered = mac.clone();
        tampered[31] ^= 0x01;
        assert!(
            !verify_hmac(&key, &data, &tampered),
            "{}: tampered mac accepted",
            v.name
        );
    }
}

#[test]
fn aes256_cbc_vectors() {
    if skip_without_corpus("aes256_cbc_vectors") {
        return;
    }
    for v in load::<AesCbcVector>("aes256_cbc.json").vectors {
        let key = unhex("key", &v.name, &v.key);
        let iv = unhex("iv", &v.name, &v.iv);
        let plaintext = unhex("plaintext", &v.name, &v.plaintext);
        let padded = unhex("padded_plaintext", &v.name, &v.padded_plaintext);
        let ciphertext = unhex("ciphertext", &v.name, &v.ciphertext);
        assert_eq!(padded.len(), ciphertext.len(), "{}", v.name);

        let mut enc = vec![0u8; plaintext.len() + 16];
        let enc_len = aes256_cbc_encrypt(&key, &iv, &plaintext, &mut enc)
            .unwrap_or_else(|e| panic!("{}: encrypt failed: {e}", v.name));
        assert_eq!(
            &enc[..enc_len],
            ciphertext,
            "{}: ciphertext mismatch",
            v.name
        );

        let mut dec = vec![0u8; ciphertext.len()];
        let dec_len = aes256_cbc_decrypt(&key, &iv, &ciphertext, &mut dec)
            .unwrap_or_else(|e| panic!("{}: decrypt failed: {e}", v.name));
        assert_eq!(&dec[..dec_len], plaintext, "{}: plaintext mismatch", v.name);
    }
}

#[test]
fn token_vectors() {
    if skip_without_corpus("token_vectors") {
        return;
    }
    for v in load::<TokenVector>("token.json").vectors {
        let key = unhex("key", &v.name, &v.key);
        let token = unhex("token", &v.name, &v.token);

        let expected_plaintext = match v.operation.as_str() {
            "roundtrip" => {
                let plaintext = unhex(
                    "plaintext",
                    &v.name,
                    v.plaintext
                        .as_deref()
                        .expect("roundtrip vector without plaintext"),
                );
                let iv = unhex("iv", &v.name, &v.iv);
                let mut enc = vec![0u8; token.len()];
                let enc_len = encrypt_token(&key, &iv, &plaintext, &mut enc)
                    .unwrap_or_else(|e| panic!("{}: encrypt_token failed: {e}", v.name));
                assert_eq!(&enc[..enc_len], token, "{}: token bytes mismatch", v.name);
                plaintext
            }
            "decrypt" => unhex(
                "expected_plaintext",
                &v.name,
                v.expected_plaintext
                    .as_deref()
                    .expect("decrypt vector without expected_plaintext"),
            ),
            other => panic!("{}: unknown operation {other}", v.name),
        };

        let mut dec = vec![0u8; token.len()];
        let dec_len = decrypt_token(&key, &token, &mut dec)
            .unwrap_or_else(|e| panic!("{}: decrypt_token failed: {e}", v.name));
        assert_eq!(
            &dec[..dec_len],
            expected_plaintext,
            "{}: plaintext mismatch",
            v.name
        );
    }
}

#[test]
fn destination_hash_vectors() {
    if skip_without_corpus("destination_hash_vectors") {
        return;
    }
    for v in load::<DestinationVector>("destination_hash.json").vectors {
        let expected = unhex("destination_hash", &v.name, &v.destination_hash);
        let aspects: Vec<&str> = v.aspects.iter().map(String::as_str).collect();

        let destination = match &v.identity_public_key {
            Some(public_key) => {
                let public_key = unhex("identity_public_key", &v.name, public_key);
                let identity = Identity::from_public_key_bytes(&public_key)
                    .unwrap_or_else(|e| panic!("{}: identity load failed: {e:?}", v.name));
                let identity_hash = unhex(
                    "identity_hash",
                    &v.name,
                    v.identity_hash.as_deref().expect("identity without hash"),
                );
                assert_eq!(
                    identity.hash().as_slice(),
                    identity_hash,
                    "{}: identity hash mismatch",
                    v.name
                );
                Destination::new(
                    Some(identity),
                    Direction::In,
                    DestinationType::Single,
                    &v.app_name,
                    &aspects,
                )
            }
            None => Destination::new(
                None,
                Direction::In,
                DestinationType::Plain,
                &v.app_name,
                &aspects,
            ),
        }
        .unwrap_or_else(|e| panic!("{}: destination creation failed: {e:?}", v.name));

        assert_eq!(
            destination.hash().as_ref() as &[u8],
            expected,
            "{}: destination hash mismatch",
            v.name
        );
    }
}

#[test]
fn packet_hash_vectors() {
    if skip_without_corpus("packet_hash_vectors") {
        return;
    }
    for v in load::<PacketVector>("packet_hash.json").vectors {
        let raw = unhex("raw", &v.name, &v.raw);
        let expected = unhex("packet_hash", &v.name, &v.packet_hash);
        assert_eq!(packet_hash(&raw).as_slice(), expected, "{}", v.name);
    }
}
