#!/bin/bash
# _emit-auto-bug-bundle.sh — write a failure-context bundle for the
# coder bridge after a tier-runner reports RED.
#
# Usage: bash scripts/_emit-auto-bug-bundle.sh <tier-name> <log-path>
#
# Examples:
#   bash scripts/_emit-auto-bug-bundle.sh tier1     ~/.local/state/leviculum-ci/tier1-20260504-235959-12345.log
#   bash scripts/_emit-auto-bug-bundle.sh tier2     ~/.local/state/leviculum-ci/tier2-20260504-235959-12345.log
#   bash scripts/_emit-auto-bug-bundle.sh tier3-hw  ~/.local/state/leviculum-ci/nightly-hw-20260504-235959-12345.log
#
# Writes $BRIDGE/auto-bug/instructions.md (overwriting any prior
# bundle).  Run `just spawn-coder` to promote the bundle to the
# coder bridge at $BRIDGE/instructions.md.
# BRIDGE defaults to ~/.local/state/leviculum (override via
# LEVICULUM_BRIDGE).
#
# Defensive degradation: every capture step is best-effort.  If any
# input (log file, git log, cargo failure pattern) is missing or
# unreadable, the bundle falls back to a "[…unavailable…]" placeholder
# and continues.  The bundle is always emitted with a usable
# conventions block for the receiving coder, even when partial.
#
# Empirical-iteration plan: per Stage-0 §B-5, the bundle template
# should be revisited after ~5 real RED bundles have been generated
# and reviewed.  Keep the structure stable until then; resist scope
# creep.

set -u  # set -e is intentionally NOT used — defensive degradation
        # requires capture failures to fall through, not abort.

TIER="${1:-}"
LOG_PATH="${2:-}"

if [[ -z "$TIER" || -z "$LOG_PATH" ]]; then
    echo "ERROR: usage: $0 <tier-name> <log-path>" >&2
    exit 2
fi

BRIDGE="${LEVICULUM_BRIDGE:-$HOME/.local/state/leviculum}"
BUNDLE_DIR="$BRIDGE/auto-bug"
BUNDLE_FILE="$BUNDLE_DIR/instructions.md"

mkdir -p "$BUNDLE_DIR"

NOW=$(date -Iseconds)

# --- Section: failing test names ---
# Cargo emits one line per failed test in the form
#   test foo::bar::test_name ... FAILED
# plus a "failures:" block at the end with the same names indented.
# Grep the leading-`test`-style line to capture the dotted path.
if [[ -r "$LOG_PATH" ]]; then
    FAILING_TESTS=$(grep -E '^test .+ \.\.\. FAILED$' "$LOG_PATH" 2>/dev/null \
        | sed -E 's/^test (.+) \.\.\. FAILED$/  - \1/' \
        | sort -u)
    if [[ -z "$FAILING_TESTS" ]]; then
        FAILING_TESTS="  [no test failures matched the standard cargo pattern; check the log directly]"
    fi
else
    FAILING_TESTS="  [log file unavailable — cannot list failing tests]"
fi

# --- Section: recent commits ---
RECENT_COMMITS=$(git log -10 --oneline 2>/dev/null || true)
if [[ -z "$RECENT_COMMITS" ]]; then
    RECENT_COMMITS="[git log -10 --oneline unavailable]"
fi

# --- Section: first failing test stderr block ---
# Cargo prints per-failure stderr in a block fenced by
#   ---- foo::bar::test_name stdout ----
# followed by the panic + backtrace, terminated by a blank line
# before the next "---- ..." or "failures:" section.  Grab the
# first such block (~50 lines is generous for one test).
if [[ -r "$LOG_PATH" ]]; then
    FIRST_FAIL_STDERR=$(awk '/^---- .+ stdout ----$/,/^$/' "$LOG_PATH" 2>/dev/null \
        | head -50)
    if [[ -z "$FIRST_FAIL_STDERR" ]]; then
        FIRST_FAIL_STDERR="[no \`---- … stdout ----\` block found in log; failure may have happened outside cargo's test phase]"
    fi
else
    FIRST_FAIL_STDERR="[log file unavailable]"
fi

# --- Section: log tail ---
if [[ -r "$LOG_PATH" ]]; then
    LOG_TAIL=$(tail -200 "$LOG_PATH" 2>/dev/null)
    if [[ -z "$LOG_TAIL" ]]; then
        LOG_TAIL="[log file empty]"
    fi
else
    LOG_TAIL="[log file unavailable at $LOG_PATH]"
fi

# --- Write bundle ---
cat > "$BUNDLE_FILE" <<EOF
# Auto-bug bundle — $TIER RED

Generated by \`scripts/_emit-auto-bug-bundle.sh\` on $NOW.
Triggered by: \`$TIER\` RED at $LOG_PATH.

## Failing tests

$FAILING_TESTS

## Recent commits (last 10)

\`\`\`
$RECENT_COMMITS
\`\`\`

## Log excerpt — first failing test stderr

\`\`\`
$FIRST_FAIL_STDERR
\`\`\`

## Log excerpt — last 200 lines

\`\`\`
$LOG_TAIL
\`\`\`

## Conventions for the receiving coder

- Read \`CLAUDE.md\` before starting; especially §Test discipline
  and §Protocol debugging discipline.
- Per-bug context lives at \`~/.claude/bugs/<N>.md\` with the
  schema documented at \`~/.claude/bugs/README.md\`.  Consult the
  relevant entry if one exists for the failing area.
- Tests are never flaky — failures are real bugs.
- Pre-existing fail is no excuse; a red test is a stop-the-line
  signal.
- Minimal-test-first is the default: write the failing test
  before the fix.
- Full log: \`$LOG_PATH\` on schneckenschreck if you need more
  context than the excerpts above.

When ready to begin, write your plan / pre-review to
\`$BRIDGE/report.md\` per the standard bridge protocol.
EOF

echo "[auto-bug] bundle written: $BUNDLE_FILE"
